### PR TITLE
Jupyterlab 3 support

### PR DESCRIPTION
**Pull request by manics**
Adds dependency versions from https://github.com/jupyterlab/jupyterlab/blob/v3.0.0a10/dev_mode/package.json
Compare with https://github.com/jupyterlab/jupyterlab/blob/v2.2.0/dev_mode/package.json

This will hopefully work with both JupyterLab 2 and 3.

### CODE REVIEW

**Comment by manics** [comment]
Tests are failing due to https://github.com/jupyterlab/jupyterlab/issues/8833

**Comment by betatim** [comment]
That is one chatty GH action :D

**Comment by manics** [comment]
@betatim It is! it's OK where people open a PR and push very few updates, not so good on something like this. I'd like to look into replacing it with a GitHub Action with parameters to configure it's chattiness...

**Comment by betatim** [comment]
I think bots that update their comment is the way to go instead of posting a new comment each time.

**Comment by manics** [comment]
@betatim I think I've silenced the bot by replacing it with https://github.com/manics/action-binderbadge :smile:

**Comment by manics** [comment]
JupyterLab 3 is now on rc7 and should be pretty stable, so merging.

**Pull request merged**
